### PR TITLE
Feature 26-Tournaments_Tab

### PR DESCRIPTION
**Pull request by Technopeon**

### CODE REVIEW

**Comment by micheljung** [comment]
Is this a placeholder?

**Comment by Cheyans** [comment]
To my understanding yes

**Comment by Cheyans** [comment]
@Technopeon are you still working on this?

**Comment by Technopeon** [comment]
Yes, I am almost ready to start testing the python web api part of it.  I have not started on the java yet.
 

    On Wednesday, January 27, 2016 12:14 PM, Cheyan Setayesh <notifications@github.com> wrote:
 

 @Technopeon are you still working on this?—

**Comment by micheljung** [comment]
Can you translate "almost ready" into a time span? x)

**Pull request closed without merging**
